parameters:
#    abc_contact_us.example.class: ABC\ContactUsBundle\Example

services:
#    abc_contact_us.example:
#        class: %abc_contact_us.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
