abc_application:
    resource: "@ABCApplicationBundle/Resources/config/routing.yml"
    prefix:   /applicant

abc_rsp:
    resource: "@ABCRspBundle/Resources/config/routing.yml"
    prefix:   /rsp

abc_style:
    resource: "@ABCStyleBundle/Resources/config/routing.yml"
    prefix:   /

abc_admin_resource_admin:
    resource: "@ABCAdminResourceAdminBundle/Resources/config/routing.yml"
    prefix:   /

abc_admin_course_admin:
    resource: "@ABCAdminCourseAdminBundle/Resources/config/routing.yml"
    prefix:   /


