abc_home:
    resource: "@ABCHomeBundle/Resources/config/routing.yml"
    prefix:   /





abc_course:
    resource: "@ABCCourseBundle/Resources/config/routing.yml"
    prefix:   /course

abc_application:
    resource: "@ABCApplicationBundle/Resources/config/routing.yml"
    prefix:   /application
    
abc_rsp:
    resource: "@ABCRspBundle/Resources/config/routing.yml"
    prefix:   /rsp

abc_style:
    resource: "@ABCStyleBundle/Resources/config/routing.yml"
    prefix:   /

abc_admin_resource_admin:
    resource: "@ABCAdminResourceAdminBundle/Resources/config/routing.yml"
    prefix:   /resourceAdmin

abc_admin_course_admin:
    resource: "@ABCAdminCourseAdminBundle/Resources/config/routing.yml"
    prefix:   /courseAdmin
    
abc_admin_resource_admin_department:
        resource: "@ABCAdminResourceAdminBundle/Resources/config/routing/department.yml"
        prefix:   /resourceAdmin/department

