abc_home:
    resource: "@ABCHomeBundle/Resources/config/routing.yml"
    prefix:   /

abc_course:
    resource: "@ABCCourseBundle/Resources/config/routing.yml"
    prefix:   /course

abc_application:
    resource: "@ABCApplicationBundle/Resources/config/routing.yml"
    prefix:   /application
    
abc_rsp:
    resource: "@ABCRspBundle/Resources/config/routing.yml"
    prefix:   /rsp

abc_style:
    resource: "@ABCStyleBundle/Resources/config/routing.yml"
    prefix:   /

abc_admin_resource_admin:
    resource: "@ABCAdminResourceAdminBundle/Resources/config/routing.yml"
    prefix:   /resourceAdmin

abc_admin_course_admin:
    resource: "@ABCAdminCourseAdminBundle/Resources/config/routing.yml"
    prefix:   /courseAdmin
#resource admin - Department    
abc_admin_resource_admin_department: 
        resource: "@ABCAdminResourceAdminBundle/Resources/config/routing/department.yml"
        prefix:   /resourceAdmin/department

abc_rating:
    resource: "@ABCRatingBundle/Resources/config/routing.yml"
    prefix:   /rating
    
#resource admin - Class    
abc_admin_resource_admin_class:
        resource: "@ABCAdminResourceAdminBundle/Resources/config/routing/class.yml"
        prefix:   /resourceAdmin/class  
        
#resource admin - Timeslot   
abc_admin_resource_admin_timeslot:
        resource: "@ABCAdminResourceAdminBundle/Resources/config/routing/timeslot.yml"
        prefix:   /resourceAdmin/timeslot 
        
#resource admin - Session   
abc_admin_resource_admin_session:
        resource: "@ABCAdminResourceAdminBundle/Resources/config/routing/session.yml"
        prefix:   /resourceAdmin/session

abc_home_contact:
    resource: "@ABCHomeBundle/Resources/config/Contact/routing.yml"
    prefix:   /contact
    
abc_admin_course_admin_selection:
        resource: "@ABCAdminCourseAdminBundle/Resources/config/routing.yml"
        prefix:   /courseAdmin/selection
