abc_application_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ABCApplicationBundle:Default:index }
    
application:
    pattern:  /
    defaults: { _controller: ABCApplicationBundle:Application:index }
    
application_new:
    pattern:  /step1
    defaults: { _controller: ABCApplicationBundle:Application:new }

application_newC:
    pattern:  /step1/{courseId}
    defaults: { _controller: ABCApplicationBundle:Application:newGivenCourse }
    
application_create:
    pattern: /new/create
    defaults: { _controller: ABCApplicationBundle:Application:create }
    requirements: { _method: POST }

application_show:
    pattern: /show/{id}
    defaults: { _controller: ABCApplicationBundle:Application:show } 
    
application_edit:
    pattern: /edit/{id}
    defaults: { _controller: ABCApplicationBundle:Application:edit}
    
application_update:
    pattern: /update/{id}
    defaults: { _controller: ABCApplicationBundle:Application:update}
    requirements: { _method: post|put }
    
application_delete:
    pattern: /delete/{id}
    defaults: { _controller: ABCApplicationBundle:Application:delete}
    requirements: { _method: post|delete }
    
application_pref:
    pattern: /pref/{id}
    defaults: { _controller: ABCApplicationBundle:Application:pref } 

application_pref_update:
    pattern: /pref_update
    defaults: { _controller: ABCApplicationBundle:Application:updatePref }
    requirements: { _method: POST}
