parameters:
#    abc_admin_course_admin.example.class: ABC\Admin\CourseAdminBundle\Example

services:
#    abc_admin_course_admin.example:
#        class: %abc_admin_course_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
